# Generated by Django 5.0.4 on 2024-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1@qq.com', max_length=254, verbose_name='注册邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='场务人员', max_length=10, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
    ]
