# Generated by Django 5.0.4 on 2024-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_user_email_user_phone_user_type_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='1@qq.com', max_length=30, verbose_name='注册邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='场务人员', max_length=20, verbose_name='身份'),
        ),
    ]
