# Generated by Django 5.0.4 on 2024-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userLogin", "0003_alter_user_email_alter_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="warn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warningname", models.CharField(max_length=20)),
                ("warningtime", models.CharField(max_length=50)),
                (
                    "savepath",
                    models.ImageField(
                        upload_to="D:/summerProject2024/video/yolov5/warning"
                    ),
                ),
                ("done", models.IntegerField(default=0)),
            ],
        ),
    ]
