# Generated by Django 4.2.14 on 2024-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('faceSave', models.ImageField(upload_to='D:/summerProject2024/video/faceRecog/data/data_faces_from_camera')),
            ],
        ),
    ]
